title: "Children Of U"
description: "Voluntariado Missionário no Uganda - 2017"
lang: "pt"
baseurl: "https://childrenofu.github.io/"
url: "https://childrenofu.github.io/"
author: "Afonso Silva"
email: "vm.uganda2017@gmail.com"
facebook: "facebook.com/childrenofU/"
github_username: "childrenofu"
phone: "+351 911 957 870"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
